/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package NativeExchange;
import java.sql.*;
import javax.swing.*;

/**
 *
 * @author Albin
 */
public class AddListingPanel extends javax.swing.JPanel {

    private final int userId;
    /**
     * Creates new form AddListingPanel
     */
    public AddListingPanel(int userId) {
        this.userId = userId;
        initComponents();
        loadCategories();
    }
    
    private void loadCategories() {
        try (Connection con = DBConnect.getConnection()) {
            String sql = "SELECT category_id, category_name FROM categories";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                categoryChoice.addItem(
                    new CategoryItem(
                        rs.getInt("category_id"),
                        rs.getString("category_name")
                    )
                );
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    class CategoryItem {
        int id;
        String name;
        CategoryItem(int id, String name) {
            this.id = id;
            this.name = name;
        }
        @Override
        public String toString() {
            return name;
        }
    }

    
    private void addListing() {
        try {
            String itemName = itemnametxt.getText().trim();
            int quantity = Integer.parseInt(quantitytxt.getText().trim());
            String location = locationtxt.getText().trim();

            CategoryItem selected = (CategoryItem) categoryChoice.getSelectedItem();

            try (Connection con = DBConnect.getConnection()) {

                String sql = """
                    INSERT INTO listings
                    (listing_id, vendor_id, category_id,
                     item_name, quantity, location, status_id)
                    VALUES
                    (seq_listings.NEXTVAL, ?, ?, ?, ?, ?, 1)
                """;

                PreparedStatement ps = con.prepareStatement(sql);

                ps.setInt(1, userId);
                ps.setInt(2, selected.id);
                ps.setString(3, itemName);
                ps.setInt(4, quantity);
                ps.setString(5, location);

                ps.executeUpdate();
            }

            JOptionPane.showMessageDialog(this, "Listing added successfully");

            itemnametxt.setText("");
            quantitytxt.setText("");
            locationtxt.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid input");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        itemnametxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        categoryChoice = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        quantitytxt = new javax.swing.JTextField();
        locationtxt = new javax.swing.JTextField();
        addItem = new javax.swing.JButton();

        jLabel1.setText("Item Name:");

        itemnametxt.addActionListener(this::itemnametxtActionPerformed);

        jLabel2.setText("Category:");

        categoryChoice.addActionListener(this::categoryChoiceActionPerformed);

        jLabel3.setText("Quantity:");

        jLabel4.setText("Location");

        locationtxt.addActionListener(this::locationtxtActionPerformed);

        addItem.setText("Add");
        addItem.addActionListener(this::addItemActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(locationtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(itemnametxt)
                                .addComponent(categoryChoice, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(quantitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addItem)
                        .addGap(14, 14, 14)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(itemnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(categoryChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(quantitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(locationtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addItem)
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void itemnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemnametxtActionPerformed

    private void locationtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationtxtActionPerformed

    private void addItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemActionPerformed
        // TODO add your handling code here:
        addListing();
    }//GEN-LAST:event_addItemActionPerformed

    private void categoryChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryChoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryChoiceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItem;
    private javax.swing.JComboBox<Object> categoryChoice;
    private javax.swing.JTextField itemnametxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField locationtxt;
    private javax.swing.JTextField quantitytxt;
    // End of variables declaration//GEN-END:variables
}
