/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package NativeExchange;
import javax.swing.table.*;
import javax.swing.*;
import java.sql.*;

/**
 *
 * @author Albin
 */
public class AdminListingsPanel extends javax.swing.JPanel {
    
    private DefaultTableModel model;
    /**
     * Creates new form AdminListingsPanel
     */
    public AdminListingsPanel() {
        initComponents();
        model = (DefaultTableModel) listingTable.getModel();
        loadListings();
   }
    
    public void loadListings() {
        model.setRowCount(0);
        try (Connection con = DBConnect.getConnection()) {
            String sql = """
                SELECT l.listing_id,
                       l.item_name,
                       u.username AS vendor,
                       c.category_name,
                       l.quantity,
                       l.location,
                       s.status_name
                FROM listings l
                JOIN users u ON l.vendor_id = u.user_id
                JOIN categories c ON l.category_id = c.category_id
                JOIN listing_status s ON l.status_id = s.status_id
                ORDER BY l.created_date DESC
            """;
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("listing_id"),
                    rs.getString("item_name"),
                    rs.getString("vendor"),
                    rs.getString("category_name"),
                    rs.getInt("quantity"),
                    rs.getString("location"),
                    rs.getString("status_name")
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading listings");
        }
    }
    
    
    public void refresh() {
        loadListings();
    }
    
    private void updateListingStatus() {
        int selectedRow = listingTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Select a listing first");
            return;
        }

        int listingId = (int) model.getValueAt(selectedRow, 0);
        String currentStatus = (String) model.getValueAt(selectedRow, 6);

        int newStatusId;

        if (currentStatus.equals("AVAILABLE")) {
            newStatusId = 3; // CLOSED
        } else if (currentStatus.equals("CLOSED")) {
            newStatusId = 1; // AVAILABLE
        } else {
            JOptionPane.showMessageDialog(this, "Cannot modify SOLD listings");
            return;
        }

        try (Connection con = DBConnect.getConnection()) {
            String sql = """
                UPDATE listings
                SET status_id = ?
                WHERE listing_id = ?
            """;
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, newStatusId);
            ps.setInt(2, listingId);
            ps.executeUpdate();
            loadListings();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error updating listing");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listingTable = new javax.swing.JTable();
        refreshButton = new javax.swing.JButton();
        statusButton = new javax.swing.JButton();

        listingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Listing ID", "Item Name", "Vendor", "Category", "Quantity", "Location", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(listingTable);

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(this::refreshButtonActionPerformed);

        statusButton.setText("Change Status");
        statusButton.addActionListener(this::statusButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(statusButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshButton)
                    .addComponent(statusButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void statusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButtonActionPerformed
        // TODO add your handling code here:
        updateListingStatus();
        refresh();
    }//GEN-LAST:event_statusButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_refreshButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listingTable;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton statusButton;
    // End of variables declaration//GEN-END:variables
}
