/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package NativeExchange;
import javax.swing.table.*;
import javax.swing.*;
import java.sql.*;

/**
 *
 * @author Albin
 */
public class AdminUsersPanel extends javax.swing.JPanel {

    private int userId;
    private DefaultTableModel model;
    /**
     * Creates new form AdminUsersPanel
     */
    public AdminUsersPanel(int userId) {
        this.userId = userId;
        initComponents();
        model = (DefaultTableModel) userTable.getModel();
        loadUsers();
    }        

    public void loadUsers() {

        model.setRowCount(0);

        try (Connection con = DBConnect.getConnection()) {

            String sql = """
                SELECT u.user_id,
                       u.username,
                       r.role_name,
                       u.status
                FROM users u
                JOIN roles r ON u.role_id = r.role_id
                ORDER BY u.user_id
            """;

            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("user_id"),
                    rs.getString("username"),
                    rs.getString("role_name"),
                    rs.getString("status")
                });
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading users");
        }
    }
    
    public void refresh() {
        loadUsers();
    }

    private void updateUserStatus() {
        int selectedRow = userTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Select a user first");
            return;
        }

        int selected_userId = (int) model.getValueAt(selectedRow, 0);
        String currentStatus = (String) model.getValueAt(selectedRow, 3);
        if(this.userId == selected_userId) {
            JOptionPane.showMessageDialog(this, "You cannot deactivate your own account");
            return;
        }
        if (currentStatus == null) {
            JOptionPane.showMessageDialog(this, "Invalid status");
            return;
        }

        // Toggle logic
        String newStatus = currentStatus.equals("ACTIVE") ? "INACTIVE" : "ACTIVE";

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Change user status to " + newStatus + "?",
                "Confirm",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION)
            return;

        String sql = """
            UPDATE users
            SET status = ?
            WHERE user_id = ?
        """;

        try (Connection con = DBConnect.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setString(1, newStatus);
            ps.setInt(2, selected_userId);

            int rowsAffected = ps.executeUpdate();

            if (rowsAffected > 0) {
                // Update table without reloading everything
                model.setValueAt(newStatus, selectedRow, 3);
                JOptionPane.showMessageDialog(this, "User status updated");
            } else {
                JOptionPane.showMessageDialog(this, "User not found");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error updating user: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        statusButton = new javax.swing.JButton();
        refreshbutton = new javax.swing.JButton();

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "User ID", "Username", "Role", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(userTable);

        statusButton.setText("Change Status");
        statusButton.addActionListener(this::statusButtonActionPerformed);

        refreshbutton.setText("Refresh");
        refreshbutton.addActionListener(this::refreshbuttonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(statusButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshbutton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusButton)
                    .addComponent(refreshbutton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void statusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButtonActionPerformed
        // TODO add your handling code here:
        updateUserStatus();
        refresh();
    }//GEN-LAST:event_statusButtonActionPerformed

    private void refreshbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbuttonActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_refreshbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshbutton;
    private javax.swing.JButton statusButton;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
