/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package NativeExchange;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;

/**
 *
 * @author Albin
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    private final int userId;
    private final int roleId;
    private ViewListingsPanel viewListingsPanel;
    private MyRequestsPanel myRequestsPanel;
    private VendorListingsPanel listingsPanel;
    private AddListingPanel addListingPanel;
    private ManageRequestsPanel manageRequestsPanel;
    private AdminUsersPanel adminUserPanel;
    private AdminListingsPanel adminListingPanel;


    private Dashboard() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
   
    /**
     * Creates new form Dashboard1
     * @param userId
     * @param roleId
     */
    public Dashboard(int userId, int roleId) {
        initComponents();
        this.userId = userId;
        this.roleId = roleId;
        loadProfileInfo();
        applyRoleRestrictions();
        viewListingsPanel = new ViewListingsPanel(userId);
        mainPanel.add(viewListingsPanel,"VIEW_LISTING");
        myRequestsPanel = new MyRequestsPanel(userId);
        mainPanel.add(myRequestsPanel, "MY_REQUESTS");
        listingsPanel = new VendorListingsPanel(userId);
        mainPanel.add(listingsPanel, "LISTINGS");
        addListingPanel = new AddListingPanel(userId);
        mainPanel.add(addListingPanel,"ADD_LISTING");
        manageRequestsPanel = new ManageRequestsPanel(userId);
        mainPanel.add(manageRequestsPanel, "MANAGE_REQUESTS");
        adminUserPanel = new AdminUsersPanel(userId);
        mainPanel.add(adminUserPanel,"USERS");
        adminListingPanel = new AdminListingsPanel();
        mainPanel.add(adminListingPanel,"ADMIN_LISTING");
    }
    
    private void applyRoleRestrictions() {
        if (roleId == 1) { // ADMIN
            vendorMenu.setVisible(false);
        }
        else if (roleId == 2) { // VENDOR
            adminMenu.setVisible(false);
            listingsMenu.setVisible(false); // customer listing menu
        }
        else if (roleId == 3) { // CUSTOMER
            adminMenu.setVisible(false);
            vendorMenu.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
        
    private void loadProfileInfo() {
        Connection con = DBConnect.getConnection();
        String query = "SELECT username FROM users WHERE user_id = ?";
        PreparedStatement pst;
        try  {
            pst = con.prepareStatement(query);
            pst.setInt(1, this.userId);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                // Set the username from DB
                username.setText(rs.getString("username"));

                // Map the roleId to a String
                String roleName;
                switch (this.roleId) {
                    case 1 -> roleName = "Admin";
                    case 2 -> roleName = "Vendor";
                    case 3 -> roleName = "Customer";
                    default -> roleName = "Unknown";
                }
                role.setText(roleName);

                // Ensure fields are locked
                username.setEditable(false);
                role.setEditable(false);
            }
        } catch (SQLException e) {
            logger.log(java.util.logging.Level.SEVERE, "Database error", e);
        }
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        EmptyPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ProfilePanel = new javax.swing.JPanel();
        userlabel = new javax.swing.JLabel();
        rolelabel = new javax.swing.JLabel();
        role = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        changePassword = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        profileMenu = new javax.swing.JMenu();
        myProfile = new javax.swing.JMenuItem();
        jlogout = new javax.swing.JMenuItem();
        listingsMenu = new javax.swing.JMenu();
        viewListing = new javax.swing.JMenuItem();
        myRequests = new javax.swing.JMenuItem();
        vendorMenu = new javax.swing.JMenu();
        myListings = new javax.swing.JMenuItem();
        addListings = new javax.swing.JMenuItem();
        manageRequests = new javax.swing.JMenuItem();
        adminMenu = new javax.swing.JMenu();
        viewUsers = new javax.swing.JMenuItem();
        viewAllListings = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        jLabel1.setText("EMPTY");

        javax.swing.GroupLayout EmptyPanelLayout = new javax.swing.GroupLayout(EmptyPanel);
        EmptyPanel.setLayout(EmptyPanelLayout);
        EmptyPanelLayout.setHorizontalGroup(
            EmptyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmptyPanelLayout.createSequentialGroup()
                .addContainerGap(431, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(119, 119, 119))
        );
        EmptyPanelLayout.setVerticalGroup(
            EmptyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmptyPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addContainerGap(308, Short.MAX_VALUE))
        );

        mainPanel.add(EmptyPanel, "card3");

        userlabel.setText("Username:");

        rolelabel.setText("Role:");

        role.setEditable(false);

        username.setEditable(false);
        username.addActionListener(this::usernameActionPerformed);

        changePassword.setText("Change Password");
        changePassword.addActionListener(this::changePasswordActionPerformed);

        javax.swing.GroupLayout ProfilePanelLayout = new javax.swing.GroupLayout(ProfilePanel);
        ProfilePanel.setLayout(ProfilePanelLayout);
        ProfilePanelLayout.setHorizontalGroup(
            ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfilePanelLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rolelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changePassword)
                    .addGroup(ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        ProfilePanelLayout.setVerticalGroup(
            ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfilePanelLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userlabel)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ProfilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rolelabel)
                    .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(changePassword)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        mainPanel.add(ProfilePanel, "PROFILE");

        profileMenu.setText("Profile");

        myProfile.setText("My Profile");
        myProfile.addActionListener(this::myProfileActionPerformed);
        profileMenu.add(myProfile);

        jlogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jlogout.setText("Logout");
        jlogout.addActionListener(this::jlogoutActionPerformed);
        profileMenu.add(jlogout);

        MenuBar.add(profileMenu);

        listingsMenu.setText("Listings");
        listingsMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listingsMenuMouseClicked(evt);
            }
        });

        viewListing.setText("View Listings");
        viewListing.addActionListener(this::viewListingActionPerformed);
        listingsMenu.add(viewListing);

        myRequests.setText("My Requests");
        myRequests.addActionListener(this::myRequestsActionPerformed);
        listingsMenu.add(myRequests);

        MenuBar.add(listingsMenu);

        vendorMenu.setText("Vendor");

        myListings.setText("My Listings");
        myListings.addActionListener(this::myListingsActionPerformed);
        vendorMenu.add(myListings);

        addListings.setText("Add Listings");
        addListings.addActionListener(this::addListingsActionPerformed);
        vendorMenu.add(addListings);

        manageRequests.setText("Manage Requests");
        manageRequests.addActionListener(this::manageRequestsActionPerformed);
        vendorMenu.add(manageRequests);

        MenuBar.add(vendorMenu);

        adminMenu.setText("Admin");

        viewUsers.setText("View Users");
        viewUsers.addActionListener(this::viewUsersActionPerformed);
        adminMenu.add(viewUsers);

        viewAllListings.setText("View All listing");
        viewAllListings.addActionListener(this::viewAllListingsActionPerformed);
        adminMenu.add(viewAllListings);

        MenuBar.add(adminMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(600, 400));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogoutActionPerformed
        // TODO add your handling code here:
        new LoginPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jlogoutActionPerformed

    private void listingsMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listingsMenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listingsMenuMouseClicked

    private void viewListingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewListingActionPerformed
        // TODO add your handling code here:
        
        java.awt.CardLayout cl = (java.awt.CardLayout) mainPanel.getLayout();
        viewListingsPanel.refresh();   // refresh data
        cl.show(mainPanel, "VIEW_LISTING");

    }//GEN-LAST:event_viewListingActionPerformed

    private void myRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myRequestsActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout cl = (java.awt.CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "MY_REQUESTS");
        myRequestsPanel.refresh();
        
    }//GEN-LAST:event_myRequestsActionPerformed

    private void myProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myProfileActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout cl = (java.awt.CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "PROFILE");
        loadProfileInfo();
    }//GEN-LAST:event_myProfileActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void changePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordActionPerformed
        // TODO add your handling code here:
        ChangePassword dialog = new ChangePassword(this, true, this.userId);
        dialog.setLocationRelativeTo(this); // Optional: Centers the dialog over your main window
        dialog.setVisible(true); 
    }//GEN-LAST:event_changePasswordActionPerformed

    private void addListingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addListingsActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout cl = (java.awt.CardLayout) mainPanel.getLayout();
        cl.show(mainPanel, "ADD_LISTING");
    }//GEN-LAST:event_addListingsActionPerformed

    private void myListingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myListingsActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout cl = (java.awt.CardLayout) mainPanel.getLayout();
        listingsPanel.refresh();   // refresh data
        cl.show(mainPanel, "LISTINGS");
    }//GEN-LAST:event_myListingsActionPerformed

    private void viewUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUsersActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout cl = (java.awt.CardLayout) mainPanel.getLayout();
        adminUserPanel.refresh();   // refresh data
        cl.show(mainPanel, "USERS");
    }//GEN-LAST:event_viewUsersActionPerformed

    private void viewAllListingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllListingsActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout cl = (java.awt.CardLayout) mainPanel.getLayout();
        adminListingPanel.refresh();   // refresh data
        cl.show(mainPanel, "ADMIN_LISTING");
    }//GEN-LAST:event_viewAllListingsActionPerformed

    private void manageRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageRequestsActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout cl = (java.awt.CardLayout) mainPanel.getLayout();
        manageRequestsPanel.refresh();   // refresh data
        cl.show(mainPanel, "MANAGE_REQUESTS");
    }//GEN-LAST:event_manageRequestsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        System.out.println("Dashboard cannot be opened directly. Run Login first.");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EmptyPanel;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JPanel ProfilePanel;
    private javax.swing.JMenuItem addListings;
    private javax.swing.JMenu adminMenu;
    private javax.swing.JButton changePassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jlogout;
    private javax.swing.JMenu listingsMenu;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuItem manageRequests;
    private javax.swing.JMenuItem myListings;
    private javax.swing.JMenuItem myProfile;
    private javax.swing.JMenuItem myRequests;
    private javax.swing.JMenu profileMenu;
    private javax.swing.JTextField role;
    private javax.swing.JLabel rolelabel;
    private javax.swing.JLabel userlabel;
    private javax.swing.JTextField username;
    private javax.swing.JMenu vendorMenu;
    private javax.swing.JMenuItem viewAllListings;
    private javax.swing.JMenuItem viewListing;
    private javax.swing.JMenuItem viewUsers;
    // End of variables declaration//GEN-END:variables
}
