/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package NativeExchange;

import javax.swing.table.*;
import javax.swing.*;
import java.sql.*;

/**
 *
 * @author Albin
 */
public class ManageRequestsPanel extends javax.swing.JPanel {

    private int userId;
    private DefaultTableModel model;
    
    /**
     * Creates new form ManageRequestsPanel
     */
    public ManageRequestsPanel(int userId) {
        this.userId = userId;
        initComponents();
        model = (DefaultTableModel) requestTable.getModel();
        loadRequests();
    }

    public void loadRequests() {
        model.setRowCount(0);
        try (Connection con = DBConnect.getConnection()) {
            String sql = """
                SELECT r.request_id,
                       l.item_name,
                       u.username AS customer,
                       r.request_date,
                       rs.status_name
                FROM requests r
                JOIN listings l ON r.listing_id = l.listing_id
                JOIN users u ON r.customer_id = u.user_id
                JOIN request_status rs ON r.status_id = rs.status_id
                WHERE l.vendor_id = ?
                ORDER BY r.request_date DESC
            """;

            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, userId);

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("request_id"),
                    rs.getString("item_name"),
                    rs.getString("customer"),
                    rs.getDate("request_date"),
                    rs.getString("status_name")
                });
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading requests");
        }
    }
    public void refresh() {
        loadRequests();
    }
    
    private void updateRequestStatus(int newStatusId) {

        int selectedRow = requestTable.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Select a request first");
            return;
        }

        int requestId = (int) model.getValueAt(selectedRow, 0);
        String currentStatus = (String) model.getValueAt(selectedRow, 4);

        if (!currentStatus.equals("PENDING")) {
            JOptionPane.showMessageDialog(this, "Only PENDING requests can be modified");
            return;
        }

        try (Connection con = DBConnect.getConnection()) {
            String sql = """
                UPDATE requests
                SET status_id = ?
                WHERE request_id = ?
            """;
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, newStatusId);
            ps.setInt(2, requestId);
            ps.executeUpdate();
            loadRequests();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error updating request");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();
        refreshButton = new javax.swing.JButton();
        rejectButton = new javax.swing.JButton();
        approveButton = new javax.swing.JButton();

        requestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Item Name", "Customer", "Request Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(requestTable);

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(this::refreshButtonActionPerformed);

        rejectButton.setText("Reject");
        rejectButton.addActionListener(this::rejectButtonActionPerformed);

        approveButton.setText("Approve");
        approveButton.addActionListener(this::approveButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(approveButton)
                .addGap(18, 18, 18)
                .addComponent(rejectButton)
                .addGap(18, 18, 18)
                .addComponent(refreshButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(approveButton)
                    .addComponent(rejectButton)
                    .addComponent(refreshButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectButtonActionPerformed
        // TODO add your handling code here:
        updateRequestStatus(3);
        refresh();
    }//GEN-LAST:event_rejectButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void approveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveButtonActionPerformed
        // TODO add your handling code here:
        updateRequestStatus(2);
        refresh();
    }//GEN-LAST:event_approveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton rejectButton;
    private javax.swing.JTable requestTable;
    // End of variables declaration//GEN-END:variables
}
