/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package NativeExchange;

import javax.swing.table.*;
import javax.swing.*;
import java.sql.*;

/**
 *
 * @author Albin
 */
public class MyRequestsPanel extends javax.swing.JPanel {

    private int userId;
    private DefaultTableModel model;

    /**
     * Creates new form MyRequestsPanel
     */
    public MyRequestsPanel(int userId) {
        this.userId = userId;
        initComponents();
        model = (DefaultTableModel) requestTable.getModel();

    }
    private void loadRequests() {
        model.setRowCount(0); // Clear table before loading
        try (Connection con = DBConnect.getConnection()) {
            String sql = """
                SELECT l.item_name,
                       u.username AS vendor_name,
                       r.request_date,
                       rs.status_name
                FROM requests r
                JOIN listings l ON r.listing_id = l.listing_id
                JOIN users u ON l.vendor_id = u.user_id
                JOIN request_status rs ON r.status_id = rs.status_id
                WHERE r.customer_id = ?
                ORDER BY r.request_date DESC
            """;

            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, userId);

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {

                String itemName = rs.getString("item_name");
                String vendor = rs.getString("vendor_name");
                Date date = rs.getDate("request_date");
                String status = rs.getString("status_name");

                model.addRow(new Object[]{
                    itemName,
                    vendor,
                    date,
                    status
                });
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Error loading requests");
        }
    }
    
    public void refresh() {
        loadRequests();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();

        requestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Vendor", "Request Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(requestTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable requestTable;
    // End of variables declaration//GEN-END:variables
}
