/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package NativeExchange;

import javax.swing.table.*;
import javax.swing.*;
import java.sql.*;

/**
 *
 * @author Albin
 */
public class VendorListingsPanel extends javax.swing.JPanel {

    private int userId;
    private DefaultTableModel model;

    /**
     * Creates new form VendorListingsPanel
     */
    public VendorListingsPanel(int userId) {
        this.userId = userId;
        initComponents();
        model = (DefaultTableModel) listingsTable.getModel();
        loadListings();

    }

    private void loadListings() {
        model.setRowCount(0);
        try (Connection con = DBConnect.getConnection()) {

            String sql = """
                SELECT l.listing_id,
                       l.item_name,
                       c.category_name,
                       l.quantity,
                       l.location,
                       s.status_name
                FROM listings l
                JOIN categories c ON l.category_id = c.category_id
                JOIN listing_status s ON l.status_id = s.status_id
                WHERE l.vendor_id = ?
                ORDER BY l.created_date DESC
            """;

            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, userId);

            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("listing_id"),
                    rs.getString("item_name"),
                    rs.getString("category_name"),
                    rs.getInt("quantity"),
                    rs.getString("location"),
                    rs.getString("status_name")
                });
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading listings");
        }
    }
    
    public void refresh() {
        loadListings();
    }
    
    private void updateQuantity() {
        int selectedRow = listingsTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Select a listing first");
            return;
        }
        int listingId = (int) model.getValueAt(selectedRow, 0);
        String input = JOptionPane.showInputDialog(this, "Enter new quantity:");
        if (input == null) return;
        try {
            int newQty = Integer.parseInt(input);
            try (Connection con = DBConnect.getConnection()) {

                String sql = """
                    UPDATE listings
                    SET quantity = ?
                    WHERE listing_id = ?
                    AND vendor_id = ?
                """;
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setInt(1, newQty);
                ps.setInt(2, listingId);
                ps.setInt(3, userId);
                ps.executeUpdate();
            }
            loadListings();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid quantity");
        }
    }
    
    private void markSold() {
        int selectedRow = listingsTable.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Select a listing first");
            return;
        }
        int listingId = (int) model.getValueAt(selectedRow, 0);
        try (Connection con = DBConnect.getConnection()) {
            String sql = """
                UPDATE listings
                SET status_id = 2
                WHERE listing_id = ?
                AND vendor_id = ?
            """;
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, listingId);
            ps.setInt(2, userId);
            System.out.println(sql);

            ps.executeUpdate();

            loadListings();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error updating status");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listingsTable = new javax.swing.JTable();
        updateButton = new javax.swing.JButton();
        markSold = new javax.swing.JButton();
        refreshbutton = new javax.swing.JButton();

        listingsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Listing ID", "Item Name", "Category", "Quantity", "Location", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(listingsTable);

        updateButton.setText("Update Quantity");
        updateButton.addActionListener(this::updateButtonActionPerformed);

        markSold.setText("Mark Sold");
        markSold.addActionListener(this::markSoldActionPerformed);

        refreshbutton.setText("Refresh");
        refreshbutton.addActionListener(this::refreshbuttonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(markSold)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshbutton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateButton)
                    .addComponent(markSold)
                    .addComponent(refreshbutton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        updateQuantity();
        refresh();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void markSoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markSoldActionPerformed
        // TODO add your handling code here:
        markSold();
        refresh();
    }//GEN-LAST:event_markSoldActionPerformed

    private void refreshbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbuttonActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_refreshbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listingsTable;
    private javax.swing.JButton markSold;
    private javax.swing.JButton refreshbutton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
